### ISSUE TITLE
I can't connect my wallet from Trustwallet browser

### ISSUE THREAD

**Issue by fedemeinardo** [crypto-birds/cb-issues#1]
**Describe the bug**
I can't connect my wallet from Trustwallet browser

**To Reproduce**
1. Go to 'https://cryptobirds.com/token on Trustwallet browser'
2. Click on 'Connect'
3. It does nothing

**Expected behavior**
Connected Wallet.

**Smartphone (please complete the following information):**
 - Device: Moto G 31
 - OS: Android 11
 - Browser Trustwallet browser
 - Version 5.21

**Comment by Jandoria** [comment]
We are migrating from web3modal to web3-onboard. I'll close these issues for now as we should test everything again with the new system.
